### ISSUE TITLE
Question about Mailsender

### ISSUE THREAD

**Issue by dimitrisnl** [ahmetuysal/nest-hackathon-starter#23]
Hello there, fantastic starter - has really helped me studying nest.js!

I have a question about the Mailsender service as seen here https://github.com/ahmetuysal/nest-hackathon-starter/blob/b805e0640f45e543b14ca71090619bd09797d526/src/auth/auth.service.ts#L91

Why not inject it normally and use `ConfigService` for the Nodemailer env variables? Is there a benefit to import it directly?

Thanks!

**Comment by ahmetuysal** [comment]
Hi Dimitrios,

I am really glad it helped you. I think what you are suggesting is a good idea! I chose static function instead of injecting an instance at first thinking that [these are pure functions that does not share any state](https://softwareengineering.stackexchange.com/a/360546). However, after giving it a second thought I think you are right. It would be much better if we could use Nest's DI and and `ConfigService`. Also, since we are going with a regular class instance, we could share the nodemailer transport instead of creating a new one each time with ` MailSenderService.createTransporter()`.

Would you like to help me do the changes? I would really appreciate a PR.

**Comment by dimitrisnl** [comment]
Sounds good @ahmetuysal - I'll open a PR
